### ISSUE TITLE
Lots of "Warning: watch ENOSPC" warnings

### ISSUE THREAD

**Issue by binarykitchen** [gruntjs/grunt-contrib-watch#236]
Like that:

```
Running "watch" task
Waiting...Warning: watch ENOSPC

Running "watch" task
Waiting...Warning: watch ENOSPC

Running "watch" task
Waiting...Warning: watch ENOSPC

Running "watch" task
Waiting...Warning: watch ENOSPC

Running "watch" task
Waiting...Warning: watch ENOSPC

Running "watch" task
Waiting...Warning: watch ENOSPC

Running "watch" task
Waiting...Warning: watch ENOSPC

Running "watch" task
Waiting...Warning: watch ENOSPC
```

and then

```
Running "watch" task
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.EventEmitter.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1162:8)
    at Gaze._pollFile (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:319:10)
    at /home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:389:12
    at Array.forEach (native)
    at /home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:387:11
    at iterate (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:332:10)
    at Gaze.add (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:167:8)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.EventEmitter.addListener (events.js:160:15)
    at Object.fs.watchFile (fs.js:1162:8)
    at Gaze._pollFile (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:319:10)
    at /home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:389:12
    at Array.forEach (native)
    at /home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:387:11
    at iterate (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:332:10)
    at Gaze.add (/home/michael.heuberger/projects/binarykitchen/code/signdna/node_modules/gaze/lib/gaze.js:167:8)
```

increasing the limit won't help. The ENOSPC error keeps coming up always. Any clues? (older versions didn't have this)

**Comment by luisgagocasas** [comment]
Gracias @jfgodoy

**Comment by jomaora** [comment]
@jfgodoy thanks!!

**Comment by gakuba** [comment]
@jfgodoy thanks. it works on ubuntu 14.04 LTS

**Comment by Aabir1** [comment]
Thanks. It also work for me

**Comment by alejandropaciotti** [comment]
Thanks !!!

**Comment by Suresh-R-S** [comment]
Thanks

**Comment by jasonwzw** [comment]
thx, it works for me!

**Comment by omer413** [comment]
https://help.github.com/
https://github.com/contac
https://github.com/securit
https://github.com/site/privac
https://github.com/site/term
https://status.github.com
https://developer.github.com
https://training.github.com
https://shop.github.com
https://github.com/blo
https://github.com/abou
https://github.com/pricingtg////syyt

**Comment by nisdis** [comment]
I had and same issue, so I found out it was an Inode issue on my ubuntu box
run the cmd: df -h --output=source,target,ipcent,pcent

to check inode usage 
then delete all tmp files to solve the problem

**Comment by GaneshPediredla** [comment]
Same Issue I got in my linux Fedora machine. What Should I do now?
Can anyone help me out to solve this problem?

**Comment by shahfaisal91** [comment]
@jfgodoy thanks!!

**Comment by kane-thornwyrd** [comment]
@GaneshPediredla https://github.com/gruntjs/grunt-contrib-watch/issues/236#issuecomment-58895341

**Comment by GaneshPediredla** [comment]
@kane-thornwyrd thanks!!

**Comment by devendrachhaiya** [comment]
Thanks!! @kane-thornwyrd. Your solution works for me.

**Comment by kaleemullah360** [comment]
**SO suggested to do this:** `and it works too`

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

it wont produce the error again, but consume system Memory & Swap file. mine system has 4GB with 1.5GB Swap space. so can't predict about system with higher Memory that it won't let your work slow.

**Comment by eksyam** [comment]
i have same problem 
`Error: watch ../src/static ENOSPC`
solve with script `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by superdav42** [comment]
Increasing max_user_watches worked for me too. Perhaps a better error message could be emitted?
